name: Social Media Scheduler

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  scheduler:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: |
          pip install pandas
          pip install requests
          pip install gspread
          pip install oauth2client

      - name: Run Scheduler
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

          MEINL_PERC_TOKEN: ${{ secrets.MEINL_PERC_TOKEN }}
          MEINL_PERC_IG_ID: ${{ secrets.MEINL_PERC_IG_ID }}

          MEINL_CYM_TOKEN: ${{ secrets.MEINL_CYM_TOKEN }}
          MEINL_CYM_IG_ID: ${{ secrets.MEINL_CYM_IG_ID }}

          PEARL_TOKEN: ${{ secrets.PEARL_TOKEN }}
          PEARL_IG_ID: ${{ secrets.PEARL_IG_ID }}

          KM_TOKEN: ${{ secrets.KM_TOKEN }}
          KM_IG_ID: ${{ secrets.KM_IG_ID }}

          META_USER_TOKEN: ${{ secrets.META_USER_TOKEN }}
          META_APP_ID: ${{ secrets.META_APP_ID }}
          META_APP_SECRET: ${{ secrets.META_APP_SECRET }}

        run: python scheduler_v4.py
